// Module included in the following assemblies:
//
// * cli_reference/openshift_developer_cli/installing-odo.adoc     

[id="installing-odo-on-windows"]

= Installing {odo-title} on Windows

. Go to the web console of the cluster and click `?` in the top right corner, select `Command Line Tools` from the drop-down menu
. Go to `odo - Developer focused...`, click `Download odo`.
. Download the `odo-windows-amd64.exe` file and save it to the directory of your preference.
. Add the location of your `odo.exe` to your `GOPATH/bin` directory.

[discrete]
== Setting the `PATH` variable for Windows 7/8

The following example demonstrates how to set up a path variable. Your binaries can be located in any location, but this example uses C:\go-bin as the location.

. Create a folder at `C:\go-bin`.
. Right click *Start* and click *Control Panel*.
. Select *System and Security* and then click *System*.
. From the menu on the left, select the *Advanced systems settings* and click the *Environment Variables* button at the bottom.
. Select *Path* from the *Variable* section and click *Edit*.
. Click *New* and type `C:\go-bin` into the field or click *Browse* and select the directory, and click *OK*.

[discrete]
== Setting the `PATH` variable for Windows 10

Edit `Environment Variables` using search:

. Click *Search* and type `env` or `environment`.
. Select *Edit environment variables for your account*.
. Select *Path* from the *Variable* section and click *Edit*.
. Click *New* and type `C:\go-bin` into the field or click *Browse* and select the directory, and click *OK*.
