language: python
python:
 - 2.7

cache: pip

sudo: required

before_install:
 - sudo gem install asciidoctor -v 1.5.4
 - sudo gem install asciidoctor-diagram -v 1.5.4

install:
 - pip install pyyaml
 - pip install aura.tar.gz

script:
 - python build.py --distro openshift-enterprise --product "OpenShift Container Platform" --version 4.3 --no-upstream-fetch
 - python makeBuild.py

after_success:
 - bash autopreview.sh

after_failure:
 - bash autocomment.sh
